# Generated by Django 5.2 on 2025-09-21 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('HAPPY', '😊 Happy'), ('NEUTRAL', '😐 Neutral'), ('SAD', '😔 Sad'), ('EXCITED', '🤩 Excited'), ('CALM', '😌 Calm')], default='NEUTRAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='journal_entries', to='journal.tag'),
        ),
    ]
