# Generated by Django 5.2 on 2026-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_tag_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='ai_reflection',
            field=models.TextField(blank=True, help_text='AI-generated reflection on the entry', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='journal_attachments/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood_intensity',
            field=models.PositiveSmallIntegerField(default=5, help_text='Mood intensity from 1 to 10'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='AI calculated sentiment score (-1 to 1)'),
        ),
    ]
