# Generated by Django X.X on YYYY-MM-DD HH:MM
# This migration script adds default therapist users and profiles to the database.

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_therapists(apps, schema_editor):
    """
    Creates default Therapist users and their corresponding TherapistProfile instances.
    """
    User = apps.get_model('auth', 'User')
    TherapistProfile = apps.get_model('therapists', 'TherapistProfile')

    # A list of comprehensive therapist data to be added to the database.
    therapists_data = [
        {
            "user": {"username": "evelyn.reed", "first_name": "Evelyn", "last_name": "Reed", "email": "evelyn.reed@example.com"},
            "profile": {
                "license_number": "PSY12345",
                "specializations": ["CBT", "ANXIETY", "DEPRESSION"],
                "qualifications": ["PHD", "LPC"],
                "languages_spoken": ["EN", "FR"],
                "bio": "Dr. Evelyn Reed is a licensed psychologist with over 15 years of experience specializing in Cognitive Behavioral Therapy for anxiety and depression. She is dedicated to providing a supportive and non-judgmental space for her clients.",
                "years_experience": 15,
                "hourly_rate": 150.00,
                "accepts_insurance": True,
                "insurance_providers": ["Blue Cross", "Aetna", "Cigna"],
                "phone_number": "555-0101",
                "offers_video_sessions": True,
                "offers_chat_sessions": True,

                # Set verification and approval status for immediate availability
                "is_verified": True,
                "is_approved": True,
                "license_verified": True,
                "background_check_completed": True,
                "rating": 4.9,
                "total_reviews": 112,
            }
        },
        {
            "user": {"username": "samuel.chen", "first_name": "Samuel", "last_name": "Chen", "email": "samuel.chen@example.com"},
            "profile": {
                "license_number": "LCSW67890",
                "specializations": ["MINDFULNESS", "TRAUMA", "STRESS_MANAGEMENT"],
                "qualifications": ["MSW", "LCSW"],
                "languages_spoken": ["EN", "ZH"],
                "bio": "Samuel Chen is a Licensed Clinical Social Worker focusing on mindfulness-based stress reduction and trauma recovery. He helps clients build resilience and find balance in their lives.",
                "years_experience": 10,
                "hourly_rate": 120.00,
                "accepts_insurance": False,
                "phone_number": "555-0102",
                "offers_video_sessions": True,
                "offers_in_person": False,
                "is_verified": True,
                "is_approved": True,
                "license_verified": True,
                "background_check_completed": True,
                "rating": 4.8,
                "total_reviews": 88,
            }
        },
        {
            "user": {"username": "maria.garcia", "first_name": "Maria", "last_name": "Garcia", "email": "maria.garcia@example.com"},
            "profile": {
                "license_number": "LMFT11223",
                "specializations": ["FAMILY_THERAPY", "COUPLES_THERAPY", "ADOLESCENT"],
                "qualifications": ["MS_COUNSELING", "LMFT"],
                "languages_spoken": ["EN", "ES"],
                "bio": "Maria Garcia is a Licensed Marriage and Family Therapist with a passion for helping families and couples improve communication and resolve conflicts. She has extensive experience working with adolescents.",
                "years_experience": 12,
                "hourly_rate": 140.00,
                "accepts_insurance": True,
                "insurance_providers": ["Kaiser Permanente", "UnitedHealthcare"],
                "phone_number": "555-0103",
                "offers_video_sessions": True,
                "offers_in_person": True,
                "office_address": "123 Therapy Lane, Suite 100, Anytown, USA",
                "is_verified": True,
                "is_approved": True,
                "license_verified": True,
                "background_check_completed": True,
                "rating": 4.9,
                "total_reviews": 150,
            }
        },
        {
            "user": {"username": "chen.li", "first_name": "Chen", "last_name": "Li", "email": "chen.li@example.com"},
            "profile": {
                "license_number": "LPCC44556",
                "specializations": ["ADDICTION", "DBT", "GROUP_THERAPY"],
                "qualifications": ["MA_PSYCHOLOGY", "LPCC"],
                "languages_spoken": ["EN", "ZH"],
                "bio": "Chen Li specializes in addiction counseling and Dialectical Behavior Therapy. He facilitates group therapy sessions to provide a community of support for individuals on their recovery journey.",
                "years_experience": 8,
                "hourly_rate": 110.00,
                "accepts_insurance": False,
                "phone_number": "555-0104",
                "offers_video_sessions": True,
                "offers_chat_sessions": True,
                "is_verified": True,
                "is_approved": True,
                "license_verified": True,
                "background_check_completed": True,
                "rating": 4.7,
                "total_reviews": 75,
            }
        },
        {
            "user": {"username": "aisha.khan", "first_name": "Aisha", "last_name": "Khan", "email": "aisha.khan@example.com"},
            "profile": {
                "license_number": "PSYD78901",
                "specializations": ["TRAUMA", "EMDR", "GRIEF"],
                "qualifications": ["PSYD"],
                "languages_spoken": ["EN", "AR", "HI"],
                "bio": "Dr. Aisha Khan is a clinical psychologist specializing in trauma and grief counseling. She is certified in EMDR therapy and helps clients process difficult experiences in a safe environment.",
                "years_experience": 20,
                "hourly_rate": 180.00,
                "accepts_insurance": True,
                "insurance_providers": ["Aetna", "Cigna"],
                "phone_number": "555-0105",
                "offers_video_sessions": True,
                "is_verified": True,
                "is_approved": True,
                "license_verified": True,
                "background_check_completed": True,
                "rating": 5.0,
                "total_reviews": 210,
            }
        },
        {
            "user": {"username": "david.roth", "first_name": "David", "last_name": "Roth", "email": "david.roth@example.com"},
            "profile": {
                "license_number": "PSYDN9876",
                "specializations": ["EATING_DISORDERS", "SOMATIC", "BODY_IMAGE"],
                "qualifications": ["PHD", "PSYCHIATRIC_NURSE"],
                "languages_spoken": ["EN", "DE"],
                "bio": "Dr. David Roth focuses on the connection between mind and body, specializing in eating disorders and somatic therapy. He helps clients develop a healthier relationship with food and their bodies.",
                "years_experience": 18,
                "hourly_rate": 165.00,
                "accepts_insurance": False,
                "phone_number": "555-0106",
                "offers_video_sessions": True,
                "offers_in_person": True,
                "office_address": "456 Wellness Way, Healthville, USA",
                "is_verified": True,
                "is_approved": True,
                "license_verified": True,
                "background_check_completed": True,
                "rating": 4.8,
                "total_reviews": 95,
            }
        }
    ]

    for data in therapists_data:
        # Create the User object
        user_data = data["user"]
        # Use a generic, secure password for all default users.
        # They would change this upon first login in a real scenario.
        user_data['password'] = make_password('bloomtherapy123')
        
        user, created = User.objects.get_or_create(username=user_data['username'], defaults=user_data)
        
        # Create the TherapistProfile object, but only if the user was just created
        if created:
            profile_data = data["profile"]
            TherapistProfile.objects.create(user=user, **profile_data)


class Migration(migrations.Migration):

    dependencies = [
        # This should depend on your initial therapist model migration
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_therapists),
    ]
