# Generated by Django 5.2 on 2026-02-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_add_default_therapists'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='featured_image',
            field=models.ImageField(default='therapist_featured/default.png', help_text='Cinematic featured image for profile header', upload_to='therapist_featured/'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Social media links (e.g., {'linkedin': '...', 'twitter': '...'})"),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='video_intro_url',
            field=models.URLField(blank=True, help_text='Link to a video introduction (YouTube/Vimeo)', null=True),
        ),
    ]
