# Generated by Django 5.2 on 2026-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0003_therapistprofile_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='specialty_title',
            field=models.CharField(blank=True, help_text='Specific professional title (e.g., Clinical Neuropsychologist)', max_length=100),
        ),
    ]
